### ISSUE TITLE
VIPs not Working.

### ISSUE THREAD

**Issue by xFallenAge** [Greentwilight/VIPs#4]
When I press the star on a persons profile, the start either disappears or that contact won't go into the VIP list. I have VIP on too.. So I don't know what is going on with it. I also right clicked on the persons name and then pressed "Add VIP" didnt do anything.

**Comment by Curtis-D** [comment]
Fixed

**Comment by arlandcreations** [comment]
I tried clicking the star and right click their profile and adding vip but they don't get added to the list
![img_0001](https://user-images.githubusercontent.com/45061530/48538006-402e4700-e881-11e8-8c28-582eef08de88.JPG)
![img_0002](https://user-images.githubusercontent.com/45061530/48538016-47555500-e881-11e8-88cf-b752e6d5f97c.JPG)
